name: CI Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

# prevent race conditions on simultaneous merges
concurrency:
  group: release-main
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: echo "Running tests... (Pass)"

  release:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write             # required to write tags
        
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0        # recommended by some tagging actions to get full git history

      - name: Bump version and tag
        id: tag_version
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          tag_prefix: v

      - name: Create a GitHub Release
        uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b
        if: steps.tag_version.outputs.new_tag
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}

      # example of using the version
      - name: Output New Version
        run: |
          echo "The new version is ${{ steps.tag_version.outputs.new_version }}"
          echo "The new version is ${{ steps.tag_version.outputs.new_tag }}"
